-- EJERCICIO 1 --
SELECT C.APELLIDOS, C.NOMBRE, C.DNI, C.TELEFONO, V.MATRICULA, MA.MARCA, M.MODELO, VA.FECHA_ACCIDENTE, T.DESCR_ACCID, P.PROVINCIA
FROM SV_CLIENTES C JOIN SV_VEHICULOS V ON C.DNI = V.DNI JOIN SV_MODELOS M ON V.IDMODELO = M.IDMODELO 
JOIN SV_MARCAS MA ON M.IDMARCA = MA.IDMARCA JOIN SV_VEHIC_ACCID VA ON V.MATRICULA = VA.MATRICULA 
JOIN SV_TIPOSACCIDENTES T ON VA.IDACCIDENTE = T.IDACCIDENTE JOIN PROVINCIAS P ON C.IDPROVINCIA = P.IDPROVINCIA
WHERE UPPER(C.SEXO) = 'M' AND VA.FECHA_ACCIDENTE LIKE '%2021' AND UPPER(VA.RESPONSABLE) = 'S' AND UPPER(P.PROVINCIA) ='CIUDAD REAL';
-- EJERCICIO 2--
SELECT T.DESCR_ACCID, COUNT(DESCR_ACCID) AS "N� ACCIDENTES"  FROM SV_TIPOSACCIDENTES T JOIN SV_VEHIC_ACCID VA ON T.IDACCIDENTE = VA.IDACCIDENTE
GROUP BY DESCR_ACCID
HAVING COUNT(*)>3
ORDER BY T.DESCR_ACCID DESC;
-- EJERCICIO 3 --
-- SIN REFERENCIA EXTERNA --
SELECT V.MATRICULA, MA.MARCA, M.MODELO, VA.FECHA_ACCIDENTE, VA.RESPONSABLE
FROM  SV_VEHICULOS V JOIN SV_MODELOS M ON V.IDMODELO = M.IDMODELO 
JOIN SV_MARCAS MA ON M.IDMARCA = MA.IDMARCA JOIN SV_VEHIC_ACCID VA ON V.MATRICULA = VA.MATRICULA
WHERE UPPER(M.MODELO) LIKE '%GT%' AND VA.FECHA_ACCIDENTE BETWEEN TO_DATE('01/03/2019','DD/MM/YYYY') AND TO_DATE ('12/11/2021','DD/MM/YYYY')
AND MA.IDMARCA IN (SELECT M.IDMARCA FROM SV_MODELOS M GROUP BY M.IDMARCA HAVING COUNT(M.IDMARCA)>1);
-- CON REFERENCIA EXTERNA --
-- EJERCICIO 4 --
-- CON REFERENCIA EXTERNA --
SELECT C.DNI, V.MATRICULA, VA.FECHA_ACCIDENTE, T.DESCR_ACCID 
FROM  SV_CLIENTES C JOIN SV_VEHICULOS V ON C.DNI = V.DNI 
JOIN SV_VEHIC_ACCID VA ON V.MATRICULA = VA.MATRICULA JOIN SV_TIPOSACCIDENTES T ON VA.IDACCIDENTE = T.IDACCIDENTE
WHERE UPPER(C.POBLACION) = 'CIUDAD REAL' AND V.DNI IN (
                                SELECT V.DNI FROM SV_CLIENTES C JOIN SV_VEHICULOS V ON C.DNI = V.DNI  GROUP BY V.DNI HAVING COUNT(V.DNI)>1);
-- SIN REFERENCIA EXTERNA --
-- EJERCICIO 5 --
SELECT S.DESCRSEGURO, COUNT(*) AS "N� SEGUROS", SUM(S.CANTIDAD) AS "SUMA CANTIDADES" 
FROM  SV_CLIENTES C JOIN SV_VEHICULOS V ON C.DNI = V.DNI 
JOIN SV_TIPOSSEGURO S ON V.IDSEGURO = S.IDSEGURO 
WHERE UPPER(C.POBLACION) IN ('CIUDAD REAL','MIGUELTURRA','ALMAGRO','DAIMIEL')
GROUP BY S.DESCRSEGURO
HAVING AVG(S.CANTIDAD) < (SELECT SUM(S.CANTIDAD) FROM SV_TIPOSSEGURO S GROUP BY S.CANTIDAD);
