--APARTADO 1: CREACIÓN DE TABLAS
--TABLA CAMIONES
CREATE TABLE T_CAMIONES (
    MATRICULA_CAMION VARCHAR2 (12),
    MODELO VARCHAR2 (50) NOT NULL,
    POTENCIA NUMBER (5),
    TIPO_SEGURO VARCHAR2 (2),
    TIPO_CAMION NUMBER (1),
    CONSTRAINT CAMIONES_PK PRIMARY KEY (MATRICULA_CAMION),
    CONSTRAINT POTENCIA_CK CHECK (POTENCIA BETWEEN 100 AND 7000),
    CONSTRAINT SEGURO_CK CHECK (TIPO_SEGURO IN ('TR','F1','F2','TE'))
);

--TABLA RUTAS
CREATE TABLE T_RUTAS (
   MATRICULA_CAMION VARCHAR2 (12),
   FECHA_RUTA DATE NOT NULL,
   NOMBRE_CAMIONERO VARCHAR2 (75) NOT NULL,
   ORIGEN_RUTA VARCHAR2 (80) NOT NULL,
   DESTINO_RUTA VARCHAR2 (80) NOT NULL,   
   CONSTRAINT RUTAS_PK PRIMARY KEY (MATRICULA_CAMION, FECHA_RUTA),
CONSTRAINT T_CAMIONES_MATRICULA_FK FOREIGN KEY (MATRICULA_CAMION) REFERENCES T_CAMIONES (MATRICULA_CAMION),   
CONSTRAINT FECHA_RUTA_CK CHECK (FECHA_RUTA >=TO_DATE ('01/01/1980','DD/MM/YYYY') AND FECHA_RUTA <= TO_DATE ('31/12/2100', 'DD/MM/YYYY'))
);

--APARTADO 2: MODIFICACIÓN DE TABLAS
-- APARTADO 2.1
ALTER TABLE T_RUTAS DROP COLUMN NOMBRE_CAMIONERO; 

ALTER TABLE T_RUTAS ADD APELLIDO_1 VARCHAR2 (50) NOT NULL;
ALTER TABLE T_RUTAS ADD APELLIDO_2 VARCHAR2 (50) NOT NULL;
ALTER TABLE T_RUTAS ADD NOMBRE VARCHAR2 (50) NOT NULL;

-- APARTADO 2.2
   ALTER TABLE T_CAMIONES ADD CONSTRAINT CK_TIPO_CAMION CHECK (TIPO_CAMION IN (1, 2, 3, 4, 5));

-- APARTADO 2.3
ALTER TABLE  T_CAMIONES ADD ID_CAMION NUMBER (10);

ALTER TABLE T_CAMIONES DROP PRIMARY KEY CASCADE;
ALTER TABLE T_CAMIONES ADD CONSTRAINT PK_ID PRIMARY KEY (ID_CAMION);
-- APARTADO 2.4
--2.4.1
ALTER TABLE T_RUTAS DROP PRIMARY KEY;

--2.4.2
ALTER TABLE T_RUTAS DROP COLUMN MATRICULA_CAMION;
ALTER TABLE T_RUTAS ADD ID_CAMION NUMBER (10);
ALTER TABLE T_RUTAS ADD CONSTRAINT FK_ID FOREIGN KEY (ID_CAMION) REFERENCES T_CAMIONES (ID_CAMION);

--2.4.3
ALTER TABLE T_RUTAS ADD CONSTRAINT PK_ID_RUTAS PRIMARY KEY (ID_CAMION);

-- APARTADO 2.5
RENAME T_RUTAS TO T_RUTAS_REALIZADAS;

DROP TABLE T_CAMIONES;

--Al utilizar el comando anterior nos impide borrar la tabla 
--porque existe una clave ajena en la tabla rutas que hace referencia a la tabla camiones, 
--por tanto debemos usar el siguiente comando para eliminar la tabla correctamente con todas sus restricciones:
DROP TABLE T_CAMIONES CASCADE CONSTRAINTS;
--*Crearemos posteriormente otra vez la tabla camiones para hacer los ejercicios restantes de la tarea

--APARTADO 3: USUARIOS Y PERMISOS 
-- APARTADO 3.1
CREATE USER PRAC1 IDENTIFIED BY ASt24 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

-- APARTADO 3.2
GRANT CONNECT, RESOURCE TO PRAC1;

GRANT CREATE VIEW TO PRAC1;

-- APARTADO 3.3
--*Para este apartado volvemos a crear la tabla camiones

GRANT INSERT, UPDATE ON T_CAMIONES TO PRAC1 WITH GRANT OPTION;

-- APARTADO 3.4
REVOKE CONNECT, RESOURCE, CREATE VIEW FROM PRAC1;

REVOKE INSERT, UPDATE ON T_CAMIONES FROM PRAC1;

